
# 服务器端口等
server:
  port: 8080
  servlet:
    context-path: /api


# 数据库连接配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_growth_graph?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

# mapper
mybatis:
  typeAliasesPackage: com.jd.user.increase.domain
  mapperLocations: classpath:mapping/*.xml

logging:
  level:
    web: INFO